language: cpp
sudo: false
matrix:
  include:
    - os: osx
      compiler: clang
language: bash

git:
  depth: 5

before_install:
  - pwd
  - cd ../

install:
  - if [ $TRAVIS_OS_NAME == osx ]; then - HOMEBREW_NO_AUTO_UPDATE=1 brew install swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis python3 python || brew upgrade swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis python3 python || brew outdated swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis python3 python; fi
  - git clone --quiet --depth 1 git://github.com/fifengine/fifechan.git
  - if [ $TRAVIS_OS_NAME == osx ]; then mkdir build_fifechan; cd build_fifechan; cmake ../fifechan; fi
  - make -j3
  - sudo make install
  - cd /Users/travis/build/fifengine/fifengine
  - if [ $TRAVIS_OS_NAME == osx ]; then mkdir _build; cd _build; cmake -Dbuild-library=ON -DPYTHON_EXECUTABLE=/usr/local/bin/python3 -Dcegui=OFF ..; fi
  - make -j3
  - sudo make install
  - pwd

script:
  - python3 -c 'from fife import fife; print(fife.getVersion())'

notifications:
  irc: irc.freenode.org#fife
  email: false
